### ISSUE TITLE
Metadata Fields disappearing...

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#180]
The url is:
http://experient54193.tizrapublisher.com/

Metadata fields were there and then disappeared. Paul has tried to add them back again and when he does the original values show up.. until the field disappears again.

This site isn't super hot but I think he would like to get working on it today if possible. Let me know if you have any questions.

**Comment by daviddurand** [comment]
I think this is likely the result of the overlapping publish operations that I emailed you about earlier this afternoon.

I need more detail to look into fixing things, though. Are the field definitions disappearing (so that the fields don't appear in the admin) or are the values disappearing (so that they appear blank). In both cases, the bahavior may be different on the live and staging sites, and on the different parts of the the administrative display (editing page, document list, etc.).  That information can be helpful in tracking things down.

The details are complex (the database and the search engine have separate notions of transaction, which means that the metadata in the two can become inconsistent in the face of certain errors during publication). This would normally affect just a sigle document, which would have to be republished in any case. The list publish is more complex because the operations are batched for performance, and so many items are touched in one go. Unfortunately, if there are overlapping list publishing operations for the same content, these errors are both somewhat more likely, and more much more likely to affect multiple documents at a time.

The database is the authoritative source, and the text indexes can be refreshed from the database, but I need to know what is happening so as not to lose useful information.

**Comment by orangedrink** [comment]
The definitions are disappearing in the admin panel. but when we add them back in the values come back.

**Comment by daviddurand** [comment]
This is very interesting, as this is not a problem we've seen or that I would expect from the publication problem...

This is probably due to something that is being done in the interface, so please try to notice what operations may be preceding "a vanishment". If it would help, I might be able to come up with a list of field names that should be added back.

**Comment by PStokesOmni** [comment]
I just had this happen with collection metadata. on http://abaseer53944.tizrapublisher.com

**Comment by daviddurand** [comment]
Can you remember the exact sequence of operations that you were performing? Were there any error messages or other hints that something unusual might be happening?

Did you actually see data vanish after an operation, or did you just happen to notice something that may have happened sometime in the last few days or hours?

I see user-defined fields now, so I assume that you already recreated them. I'll be checking the logs.

**Comment by PStokesOmni** [comment]
Sure I had everything set up and ready to go in staging, made the design live and the collection metadata was gone. Yes I have recreated everything as this had to to proof to the customer.

**Comment by daviddurand** [comment]
So to the best of your memory, the fields may have vanished after work in presentatation manager?

Were you updating design properties, or creating design overrides for particular collections?

Sorry if it seems like all I'm doing is asking questions (that I know are very hard to answer), but this is a very rare problem, and I'm trying to get enough information to replicate it, so that I have a chance of fixing it. It may even involve a sequence of actions right in a row, or depend on the something happening to only when a publication or design is in a particular state (which may have been set up long previously). It could even conceivably depend on timing -- if for instance, some session has timed out.

**Comment by PStokesOmni** [comment]
I had created design over rides, but like I said everything worked great in stagging. then I published Presentation->Library->Save and apply to live
That is when they disappeared.

**Comment by daviddurand** [comment]
closing, as no progress or replication, in addition to many system changes since the initial report.

**Comment by daviddurand** [comment]
Another customer has seen this, so we are doing more investigation.

**Comment by GWPublisher** [comment]
Yes, we saw this issue as well. What happened was I created the fields in Document Properties, then I had gone into the Presentation tab and edited the All Users Info, and User Info pages.  Then I saved them and made them live.  The fields were still showing after that.  Later in the day, I edited the Stylesheet tab and created a static page.  That is when I saved the template again.  I also deleted some of the backups in the Library, because I had saved it numerous times.  I don’t know if the fields were still showing at that point.  I talked to another member of our team, and she said that she had published a document to staging later in the day, which probably would have been around the time that I saved the layout.  She did say that she saw the field at the time she published.  So overpublishing may have been the cause, so I thought I would mention all of that to you.
